### ISSUE TITLE
Multicontroller support

### ISSUE THREAD

**Issue by usernamesolent** [moonlight-stream/moonlight-common#16]
I am not sure if it should be here or in android section.

When playing on two controllers (wireless xbox 360 or two bluetooth, or bluetooth plus wireless xbox 360) users cannot press same button at the same time. It happens for A B X Y buttons, I am not sure how about the others.
It only happens for Android, when I am streaming to chrome extension it is working fine.
I believe it is the same for the bigger number of controllers.
It is same for every game.
For example pressing A plus A on other controller at the same time is registered only for the user which pressed it first.  
It is not an issue of my android I have tested on http://html5gamepad.com/ it is detecting press on two controllers with accuracy of 1ms.

I think there might be an issue while queuing up signals to or from android. 
When the same button (for example A) is send to or from android then the second one is dropped.

**Comment by cgutman** [comment]
Confirmed. Likely not a moonlight-common bug, probably a bug in the Android client.

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-android/commit/8aba4888e16540f571bae1a18f1d670a51bde30b
