### ISSUE TITLE
Right trigger constantly held down

### ISSUE THREAD

**Issue by coolitic** [moonlight-stream/moonlight-common#17]
This happens on both the android and the chrome client (the latter of which I dont even use a controller for). This issue does not happen if Im using the steam controller with the Link.

**Comment by cgutman** [comment]
What game are you streaming? What gamepad are you using? It's it connected to the client PC or the server?

**Comment by coolitic** [comment]
Issue is encountered on Dark Souls 2, Dark Souls 3, Metal Gear Rising, Sonic Generations and Steam Big Picture. I use moga power pro on android, and kb/m on chrome, both of which are connected to their respective clients.

**Comment by cgutman** [comment]
Do you have any gamepads connected to your server PC? If you run 'joy.cpl' on your server PC, do you see any devices there?

**Comment by coolitic** [comment]
When it's not streaming, no gamepads are listed, nor are any connected to begin with.

**Comment by coolitic** [comment]
Problem mysteriously disappeared, odd.
