### ISSUE TITLE
Request AMD VCE support

### ISSUE THREAD

**Issue by solidstudio** [moonlight-stream/moonlight-common#6]
See

https://github.com/jackun/openencodevfw

Is it possible?

**Comment by parkerlreed** [comment]
This would be fantastic. Take a lot of the load off the CPU.

**Comment by mrb113** [comment]
Moonlight is for the NVIDIA Gamestream protocol which requires an NVIDIA GPU.

**Comment by parkerlreed** [comment]
I think the idea of this was to be a request as the title states... There's no reason Moonlight would have to be limited to one protocol. From what I see nothing exists for Linux/AMD users.
